version: '3.8'

services:

  restful_api:
    image: node:20.11.1
    container_name: restful-api
    networks:
      - app
    environment:
      SECRET: ${SECRET}
      USER_DATABASE: ${USER_DATABASE}
      PASSWORD_DATABASE: ${PASSWORD_DATABASE}
      DATABASE: ${DATABASE}
      HOST_DATABASE: 'host.docker.internal'
      PORT_DATABASE: ${PORT_DATABASE}
    working_dir: /app/api
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    command: >
      sh -c "
        apk add --no-cache make gcc g++ python
        npm install 
        npm rebuild bcrypt --build-from-source
        apk del make gcc g++ python
        npm run start:server
      "

  react_app:
    build: 
      context: .
      dockerfile: Dockerfile.react
    container_name: react-app
    networks:
      - app
    environment:
      REACT_APP_API_KEY: ${REACT_APP_API_KEY}
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  cypress:
    image: cypress/included:13.6.4
    networks:
      - app
    environment:
      CYPRESS_baseUrl: "http://localhost:3000"
      api_key: ${REACT_APP_API_KEY}
    volumes:
      - .:/app
    depends_on:
      - react_app

  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    privileged: true
    restart: on-failure
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins

  socat:
    image: alpine/socat
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    networks:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:2376:2375"
    restart: always

volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jenkins:
    driver: bridge
  app:
    driver: bridge
